sudo: required
env:
  global:
    CC_TEST_REPORTER_ID=74f243d61252d77cceed36b21a35163c95b404527e746c983c155602aed25e55

addons:
  chrome: stable

language: node_js
node_js:
  - '12.15.0'

branches:
  only:
    - master
    - develop

before_script:
  - yes | npm install -g @angular/cli
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm run build:libs
  - ng test ng-sq-common
  - ng test ng-datatable
  - ng test ng-datetime-picker
  - ng test ng-sq-ui
  - ng test ng-modal

after_success:
  - ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.ng-sq-common.json coverage/ng-sq-common/lcov.info
  - ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.ng-datatable.json coverage/ng-datatable/lcov.info
  - ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.ng-datetime-picker.json coverage/ng-datetime-picker/lcov.info
  - ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.ng-sq-ui.json coverage/ng-sq-ui/lcov.info
  - ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.ng-modal.json coverage/ng-modal/lcov.info
  - ./cc-test-reporter sum-coverage coverage/codeclimate.*.json -p 5                  # Sum all coverage parts into coverage/codeclimate.json
  - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter upload-coverage; fi  # Upload coverage/codeclimate.json

